// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjymzeqocnzpjfamczka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqeW16ZXFvY256cGpmYW1jemthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MzM0MDEsImV4cCI6MjA1NTEwOTQwMX0.OrxRS40wBcwfwxIMEZDaM386kNsDZ33RlHM_yb2JWyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);